name: ditonton
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  google_fonts: ^6.3.2
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.1
  get_it: ^8.2.0
  sqflite: ^2.4.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.1
  http_certificate_pinning: ^3.0.1
  network_image_mock: ^2.1.1
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4
  firebase_crashlytics: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  sqflite_common_ffi: ^2.3.2
  bloc_test: ^9.1.5
  mockito: ^5.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - certificates/
